int get_decimal_position(char *);
int max(int, int);
char * remove_leading_zeros(char *);
void remove_ending_zeros(char *);
char * append(char *, char *);
char *substr( char *, int , int ,char , int , char );
char *prepend(char *,char *);
char * chop(char * ,int PREC);
char *int_char_array( int );
char *insert_str(char * , char *, int);
char *int_char_array( int );
char *clone ( char *  ) ;
